### ISSUE TITLE
Would it be nice to use default slot instead of remain slot?

### ISSUE THREAD

**Issue by pkradioman** [LeeBoYin/vue-layout-system#1]
It happen that I always have to figure out why the Layout does not render anything and found that I forgot to put the children components inside the remain slot, I think it would be more natural to use if it is a default slot. e.g. LayoutFlexRow which I often use.

Thank you, great components!

**Comment by LeeBoYin** [comment]
Hi @pkradioman, thanks for your feedback. I'm excited to see the first issue 😊

Your expectation sounds natural and reasonable to me, since the main contents are usually placed in the remaining space, in this case `LayoutFlexRow` should simply use the `default` slot as the `remain` slot.

I'll try to make `LayoutFlexRow` and `LayoutFlexColumn` accept both `default` slot and `remain` slot in the next release.

Thank you for your great idea!

**Comment by LeeBoYin** [comment]
This request is released in [v1.0.2](https://github.com/LeeBoYin/vue-layout-system/releases/tag/v1.0.2), please update and try!

**Comment by pkradioman** [comment]
Thanks a lot, and I'm glad to be helpful.
